#!/usr/bin/env bash 

# FIXME: Url Install vs Clone
# FIXME: TOOLBOX_PATH=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

set -e

main() {
    install
    configure
}

install() {
    # Updates
    sudo apt-get update -y
    sudo apt-get upgrade -y
    # Python3
    sudo apt-get install -y python3
    sudo apt-get install -y python3-pip
    # Github CLI
    sudo apt-get install -y gh  
    # Git
    sudo curl https://raw.githubusercontent.com/newren/git-filter-repo/main/git-filter-repo -o /usr/local/bin/git-filter-repo
    sudo chmod +x /usr/local/bin/git-filter-repo
    # Tmux
    # Fzf
}

configure() {
    SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
    find $SCRIPT_DIR/config/ -mindepth 1 -maxdepth 1 | while read line; do 
        echo $line
        cp -rf $line ~/
    done
    source ~/.bash_profile $(pwd)
    # source ~/.bash_profile && cd -
}

if [[ $# -eq 0 ]] ; then 
    main
else 
    echo "Executing: ${@}"
    eval ${@}
fi

