#!/usr/bin/env bash 

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

install() {

    PATH="$SCRIPT_DIR/tools/bin/:$PATH"
    mkdir -p $SCRIPT_DIR/tools/
    mkdir -p $SCRIPT_DIR/tools/bin/
    mkdir -p $SCRIPT_DIR/tools/lib/
    mkdir -p $SCRIPT_DIR/tools/share/
    mkdir -p $SCRIPT_DIR/tmp/
    # rm -rf $SCRIPT_DIR/tmp/*

    # TMUX
    (   
        sudo apt-get install -y libncurses-dev libevent-dev autoconf automake pkg-config
        cd $SCRIPT_DIR/tmp/ && git clone --depth 1 https://github.com/tmux/tmux.git
        cd $SCRIPT_DIR/tmp/tmux/ && sh autogen.sh && ./configure && make
        mv $SCRIPT_DIR/tmp/tmux/tmux $SCRIPT_DIR/tools/bin/
    )

    # NVIM
    ( 
        sudo apt-get install -y ninja-build gettext cmake unzip curl build-essential
        cd $SCRIPT_DIR/tmp/ && git clone --depth 1 https://github.com/neovim/neovim.git
        cd $SCRIPT_DIR/tmp/neovim/ && make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=$SCRIPT_DIR/tools/ && make install
    )

    # FZF
    (
        cd $SCRIPT_DIR/tmp/ && git clone --depth 1 https://github.com/junegunn/fzf.git 
        cd $SCRIPT_DIR/tmp/fzf/ && go build && mv ./fzf $SCRIPT_DIR/tools/bin/
    )

    sudo bash -c "echo '#!/usr/bin/env bash'       > /usr/local/bin/toolbox"
    sudo bash -c "echo '$SCRIPT_DIR/toolbox \${@}' > /usr/local/bin/toolbox"
    sudo chmod +x /usr/local/bin/toolbox

}

configure() {
    echo "toolbox run" >> ~/.bash_profile
}

run() {
    if [[ -n "${TMUX}" ]]; then return 0; fi
    # tmux start-server \; source-file $SCRIPT_DIR/config/tmux/.tmux.conf
    tmux source-file $SCRIPT_DIR/config/tmux/.tmux.conf
    tmux new-session -d -s main
    tmux send-keys -t main "source <(toolbox init) && clear" Enter
    tmux attach-session -t main
}

init() {

    # Path
    export PATH="$SCRIPT_DIR/tools/bin/:$PATH"

    # Aliases
    alias vi="$SCRIPT_DIR/tools/bin/nvim -u $SCRIPT_DIR/config/nvim/init.lua"
    alias vim="$SCRIPT_DIR/tools/bin/nvim -u $SCRIPT_DIR/config/nvim/init.lua"
    alias nvim="$SCRIPT_DIR/tools/bin/nvim -u $SCRIPT_DIR/config/nvim/init.lua"
    alias # Hack to export

    # Switch Home Directory
    if [[ "$(pwd)" == "/home/$(whoami)" ]]; then
        if [[ -n "/mnt/c/Users/$(whoami)/$(whoami)/" ]]; then
            cd /mnt/c/Users/$(whoami)/$(whoami)/
        elif [[ -n "/mnt/c/Users/$(whoami)/" ]]; then
            cd /mnt/c/Users/$(whoami)/
        fi
    fi

    # Return Bash filepath
    cat $SCRIPT_DIR/config/bash/functions
    # echo $SCRIPT_DIR/config/bash/functions
}

# FIXME: Make all variables local or global
# FIXME: Add this https://github.com/mislav/dotfiles/blob/d2af5900fce38238d1202aa43e7332b20add6205/bin/tmux-session
# git config pull.rebase false

# # Go Path
# export PATH="$PATH:/home/$(whoami)/go/bin/"

# color_init

# # Updates
# sudo apt-get update -y
# sudo apt-get upgrade -y
# # Python3
# sudo apt-get install -y python3
# sudo apt-get install -y python3-pip
# # Github CLI
# sudo apt-get install -y gh  
# # Fzf
# # FIXME: Install with tarball
# sudo apt-get-install -y fzf
# # Tmux
# sudo apt-get-install -y tmux
# # Git
# # FIXME: Add this
# # Git Filter Repo
# sudo curl https://raw.githubusercontent.com/newren/git-filter-repo/main/git-filter-repo -o /usr/local/bin/git-filter-repo
# sudo chmod +x /usr/local/bin/git-filter-repo
# # Nvim
# # FIXME: Install with tarball
# # Tmux
# # FIXME: Install with tarball
# FIXME: Bat
# FIXME: RG


# if [[ ! $# -eq 0 ]] ; then 
#     main
# else 
#     eval ${@}
# fi

eval ${@}
